sysprog21/vwifi

- .clang-format
- README.md
- scripts/verify.sh
- vwifi.c
1. Use `strspn` and `strcspn` to parsing the parameter.
2. Store the AP information into hash table which is `ap_info_hash`
> Use hash table to store AP information

- vwifi.c
In `owl_connect()`, when  `sme->ssid_len` is greater than or equal to `SSID_MAX_LENGTH`, `ssid_len` will be assign to `SSID_MAX_LENGTH`, and a buffer overflow will occur when adding NULL terminator at `owl->connecting_ssid[ssid_len]`.
> Fix possible buffer overflow

- README.md
- scripts/verify.sh
- vwifi.c
Rewriting some code with wrapper macro/function, like replacing
cfg80211_inform_bss_data() with cfg80211_inform_bss(), and so on.
I also add tsf support which provides timing information while
performing cfg80211_ops->scan() routine.
Fix possible buffer overflow by increment the size of every array
to 33, which can tolerate 32 characters (defined by IEEE 802.11
standard) plus one NULL terminator.
> Add TSF support

- .gitignore
- README.md
- scripts/verify.sh
- vwifi.c
I renamed the owl_ndev_priv_context to owl_vif in order to reveal
the structure includes all the fields which are interface-dependent.
I also moved many fields in owl_context to owl_vif to keep
owl_context interface-independent.
In order to add a virtual interface to a network namespace for testing,
every virtual interface is assigned to a specific wiphy.
For the future support for more than two interfaces, I rewrote some
code in ndo_start_xmit to fit more general circumstances.
User now can pass the module parameter "interfaces" to vwifi, and thus
the driver will generate desired number of interfaces, which are all
in STA mode. For the future support for different mode, one can implement
change_virtual_intf(), and call it through nl80211.
> Refactor and assign one wiphy to each interface

- vwifi.c
Originally, wiphy can only simulated 802.11 h/w with 2GHz band in 6th channel, and rates in 1/2/5.5/11 Mbps, which may limit someone who wants to configure with further PHY like 802.11g.
So in this commit, I extend the wiphy with the ability to simulate 1st to 14th channels in 2GHz band, and rates in 1/2/5.5/11/6/9/12/18/24/36/48/54 Mbps.
> Support more hardware features

- vwifi.c
According to this patch [1], kernel developers
prepared to replace netif_rx_ni() with netif_rx(). They modified netif_rx() and implement
netif_rx_ni() as a wrapper of netif_rx().
In the following patch [2], netif_rx_ni() was
removed. This patch was mentioned in networking
changes for 5.18.[3]
For the compatibility, I check kernel version
before calling netif_rx_ni().
[1]https://lore.kernel.org/netdev/20220202122848.647635-4-bigeasy@linutronix.de/ [2]https://lore.kernel.org/netdev/20220306215753.3156276-10-bigeasy@linutronix.de/ [3]https://lore.kernel.org/netdev/20220323180738.3978487-1-kuba@kernel.org/
> Check kernel version for netif_rx_ni()

- vwifi.c
Cfg80211 has changed function signature for cfg80211_ops->stop_ap() since kernel version 5.19.2, so make the function definition be
conditionally expanded by using the macro LINUX_VERSION_CODE and
KERNEL_VERSION(5, 19, 2).
> Update cfg80211_ops->stop_ap() API signature

- Makefile
The `$PWD` environment variable doesn't exist when we run `sudo make`, so the `PWD` in Makefile will be
evaulated to an empty string. Replace unreliable `PWD` by shell function `$(shell pwd)`.
> Replace env variable by shell function

- vwifi.c
Commit [406f42fa0d](https://scm.linefinity.com/common/linux-stable/commit/406f42fa0d3c) from linux kernel introduced a rbtree for faster Ethernet address look up. To maintain netdev->dev_addr in this tree we need to make all the writes to it go through appropriate helpers.
> Avoid directly modifying ndev->dev_addr

- vwifi.c
In PR #40, we have avoided directly accessing the `ndev->dev_addr` by replacing it with the helper function `eth_hw_addr_set()`. But this function only exists after Linux version 5.15-rc1. Keep the direct access to `ndev->dev_addr` when we're in the older Linux version.
> revert: eth_hw_addr_set not existent in older version

- README.md
The virt_wifi.c had been moved to the virtual directory.
> Fix hyperlink in README.md

- scripts/hostapd.conf
- scripts/verify.sh
- vwifi.c
Two changes were made in this commit:
(1) Passive scanning of vwifi: Once we execute hostapd to start AP mode , it will initialize an htrimer and set its countdown time to the beacon interval input by the user application. When the time is up, the callback function will be triggered, and it will Pass the AP's beacon to other stations.
(2) Supports 5 GHZ band: The frequency is calculated as 5 GHz + (5 * channel index).
Finally, some errors in vwifi will be corrected so that verify.sh can be executed correctly.
> Support passive scan

- vwifi.c
* origin size put in snprintf in function owinterface_add was wrong
* correct the size from ETH_ALEN to ETH_ALEN - 1
The origin `size` value in `snprintf` of `owinterface_add` was `ETH_ALEN`, which will only allow ETH_ALEN - 1 characters to write in the buffer when string size is too long.
However, since the buffer starts from `inf_name + 1`, which only allow `ETH_ALEN - 1` characters to be written into, plus the last character must be `'\0'`, so we should only allow `ETH_ALEN - 2` character to be written into the buffer.
That's why I create the PR and fix the `size` value to `ETH_ALEN - 1`
> Correct the used of snprintf in owinterface_add

- Makefile
- README.md
- vwifi-tool.c
- vwifi.c
Enable ability to use blacklist to block packets from specified interface.
Support blacklist in vwifi kernel module, used as interfaces pair such as "owl2 blocks owl1", allow maximum blacklist size to be 1024 bytes now and maintained as global content within struct owl_content.
Using userspace program to dynamically alter the blacklist maintaining in vwifi kernel module.
After mounting vwifi as kernel module in kernel, make sure the ping test works as normal as indicated in README.md.
compile blacklist_user.c and execute it
```
$ gcc blacklist_user.c -o blacklist_user.o
$ ./blacklist_user.o
```
After this step, we should have the blacklist loaded into vwifi kernel module.
Do the ping test again, it should block packets from the interface pair you specefied in `./scripts/blacklist.txt`. …
> Implement userspace tool to display driver status and specify blocklist

- scripts/verify.sh
Fix 'sucess' to 'success' in verify.sh.
> Fix typo in verify.sh

- README.md
- scripts/hostapd.conf
- scripts/plot_rssi.py
- scripts/verify.sh
- vwifi.c
Change prefix of functions, variables and related symbols from 'owl'
to 'vwifi', and change prefix of interface name from 'owl' to 'vw'.
Fix #52
> Enforce consistent naming scheme

- README.md
- scripts/common.sh
- scripts/verify.sh
- vwifi.c
The default phy%d naming for wiphy in linux kernel depends on the value of a static variable `wiphy_counter`. Since they never attempts to decrease the value of `wiphy_counter` even a wiphy is unregistered or freed, this behavior ensures the naming and indexing for wiphy will be absolutely unique.
However, the kernel might have other projects also utilize wiphy structure, which will cause some confusion of wiphy's index and naming when using `struct wiphy`. We implement a custom-made name "vw_phy%d" for wiphy in our project, in order to seperate the naming and indexing for `struct wiphy` in our project.
As for the troublesome behavior causing by the never-decreasing index of wiphy structure as decribed in #54 , we suggest to make some changes when doing manual testing by finding the wiphy …
> Implement customized naming for wiphy

- README.md
- vwifi-tool.c
- vwifi.c
correct `MAX_BLACKLIST_SIZE` to `MAX_BLOCKLIST_SIZE`
> Adopt more contemporary terminology

- vwifi.c
Starting from kernel version 6.7, several significant
changes have been made to the cfg80211 subsystem.
1.
The scan_width field is no longer present in the
cfg80211_inform_bss structure.
There really isn't any support for scanning at different
channel widths than 20 MHz since there's no way to set it.
2.
The parameters in the change_beacon function have been
updated to cfg80211_ap_update.
The change_beacon function now includes two additional
parameters, fils_discovery and unsol_bcast_probe_resp,
which arepart of the cfg80211_ap_update structure.
> Align with recent cfg80211 header

- vwifi-tool.c
When compiling, the following warning message is generated: "warning: ‘strncpy’ writing 1040 bytes into a region of size 1024 overflows the destination"
This is because calloc allocates NLMSG_SPACE(MAX_PAYLOAD) space for nlh, which includes the space for the header, so the actual space available for the message is only MAX_PAYLOAD.
@vax-r
> Fix buffer overflow

- README.md
1. Since the script is in the `scripts` directory, the command should match its path.
2. In the command line, the parameter `vw_phy0` for the iw command should not be prefixed with `$`, which is different from the script's syntax.
> Fix commands in top-level documentation

- vwifi.c
Using 802.11n (HT) as the PHY, configure as follows:
Modulation: 64-QAM
Data Bandwidth: 20MHz
Number of Spatial Streams: 4
According to the 802.11n (HT) modulation table, we have:
Number of Data Subcarriers: 52
Number of Coded Bits per Subcarrier per Stream: 6
Coding: $\frac{5}{6}$
OFDM Symbol Duration: 3.2 µs
Guard Interval Duration: 0.8 µs
Using these parameters and the formula, the calculated data rate is 260 Mbps, which matches the displayed result.
ref : 
[MCS Table](https://mcsindex.net/) 
Cc. @willwillhi1
> Support data rate and MCS

- scripts/verify.sh
- vwifi.c
Add `tx_power` to the virtual interface to describe the device's transmit power.
Implement `vwifi_set_tx_power` and `vwifi_get_tx_power` to correspond to [`set_tx_power` ](https://elixir.bootlin.com/linux/v6.9/source/drivers/net/wireless/microchip/wilc1000/cfg80211.c#L1655)and [`get_tx_power`](https://elixir.bootlin.com/linux/v6.9/source/drivers/net/wireless/microchip/wilc1000/cfg80211.c#L1687) in [cfg80211_ops](https://elixir.bootlin.com/linux/v6.9/source/include/net/cfg80211.h#L4574), respectively.
`vwifi_set_tx_power` can set the device's transmit power, while `vwifi_get_tx_power` can retrieve the transmit power information.
The transmit power can be set using the **iwconfig vwn txpower** command.
```
phy#12
Interface vw2
ifindex 14
wdev 0xc00000001
addr 00:76:77:32:00:00
type managed …
```
> Support transmit power

- .ci/check-format.sh
- .github/workflows/codeql.yml
- .github/workflows/main.yaml
New CodeQL analysis capabilities will only be available to users of v3.
See https://github.blog/changelog/2025-01-10-code-scanning-codeql-action-v2-is-now-deprecated/
> Migrate to CodeQL Action v2

- vwifi.c
This patch updates the call to `virtio_find_vqs()` to follow the new signature introduced in Linux 6.11, which replaces the separate `callbacks` and `names` arrays with a `struct virtqueue_info[]`.
Tested on:
- Kernel: 6.11.0
- Distro: Ubuntu 24.04
- Confirmed `vwifi.ko` builds and loads successfully
This resolves #73.
> Fix build error on Linux 6.11: update virtio_find_vqs() to use virtqueue_info

- README.md
> TYPO README

- vwifi.c
To align with the changes introduced in Linux kernel version 6.15, this commit replaces the deprecated del_timer_sync() with timer_delete_sync(), which now serves as its functional replacement. The function parameters remain unchanged, making this a direct drop-in fix.
ref:
https://github.com/torvalds/linux/commit/9b13df3fb64ee95e2397585404e442afee2c7d4f
> vwifi: Use timer_delete_sync() on Linux >= 6.1.84 for scan timers

- vwifi.c
Linux kernel 6.14 introduced an additional link_id parameter to the get_tx_power callback. This commit updates vwifi_get_tx_power to match the new prototype while preserving compatibility with earlier kernels.
ref:
https://github.com/torvalds/linux/commit/7a53af85d3bbdbe06cd47b81a6d99a04dc0a3963
> Support Linux 6.14 by about get_tx_power

- vwifi.c
Kernel 6.4+ sets .owner automatically. Remove manual assignment to avoid build issues and keep compatibility with older versions.
Reference: [sysprog21/kxo#18](https://github.com/sysprog21/kxo/pull/18)
> Drop .owner for kernel >= 6.4
